update main scripts

diff --git a/build_GEOCLIM b/build_GEOCLIM
--- a/build_GEOCLIM
+++ b/build_GEOCLIM
@@ -15,6 +15,8 @@ declare -a KNOWN_COMPILERS=('gfortran' 'ifort' 'pgfortran')
 ##                            Argument scanning                           ##
 ############################################################################
 
+bckp_args="$@"
+
 # DEFAULT VALUES
 display_help=0
 compset=""
@@ -33,6 +35,7 @@ clim_param_ending="cyclic"
 clim_param_periods=""
 # do not initialize 'ncpath' => take the environment variable if defined. If not, will be defined in the Makefile
 use_ncconfig_flags=1
+n_basin=10
 
 need_value=""
 got_option=0
@@ -59,6 +62,10 @@ do
 	    "-i"|"--interp"|"--co2-interp"|"--co2-interpolation")
 		need_value="interp"
 		;;
+
+            "-n"|"--nbasin"|"--nbasins"|"--n-basins")
+		need_value="n_basin"
+	        ;;
 
             "-p"|"--clim-param"|"--climatic-parameters")
 		need_value="clim-param"
@@ -129,6 +136,7 @@ do
 	    "compset")       compset=$1;;
 	    "res")           resolution=$1;;
 	    "interp")        interpolation=$1;;
+	    "n_basin")       n_basin=$1;;
 	    "clim-param")    clim_param=$1;;
 	    "param-ending" ) clim_param_ending=$1;;
 	    "param-periods") clim_param_periods=$1;;
@@ -215,6 +223,10 @@ then
     echo "                  default: $DEF_NDSLEVS"
     echo ""
     echo "     OPTIONAL ARGUMENTS:"
+    echo ""
+    echo "     -n|--nbasin|--nbasins|--n-basins"
+    echo "             Specify the number of oceanic basins (i.e., boxes of COMBINE module)"
+    echo "             Default: 10 (historical GEOCLIM setting)"
     echo ""
     echo "     -p|--clim-param|--climatic-parameters n1[,n2[,n3[,n4[,n5]]]]"
     echo "             Indicate dimensions length (n1, n2, ...) for additional climatic"
@@ -419,18 +431,27 @@ case $compset in
     "ECOGEO"|"COMBINE_ECOGEO_WTH:old")
         USE_DS="no"
 	USE_ECO="yes"
+	echo ""
+	echo "ECOLOGICAL NETWORK MODULE NOT IMPLEMENTED"
+	exit 0
         ;;
 
     "ECO-DSS"|"COMBINE_ECOGEO_WTH:DynSoil%steady")
         USE_DS="yes"
 	DS_MODE="steady-state"
 	USE_ECO="yes"
+	echo ""
+	echo "ECOLOGICAL NETWORK MODULE NOT IMPLEMENTED"
+	exit 0
         ;;
 
     "full"|"COMBINE_ECOGEO_WTH:DynSoil%dyn")
         USE_DS="yes"
 	DS_MODE="dynamic"
 	USE_ECO="yes"
+	echo ""
+	echo "ECOLOGICAL NETWORK MODULE NOT IMPLEMENTED"
+	exit 0
         ;;
 
     "")
@@ -510,16 +531,16 @@ then
     nDSz=$DEF_NDSLEVS
 fi
 
-# Test validity of resolution arguments
+# Test validity of resolution arguments (must all be integers)
 istat=0
-for n in $nco2 $nx $ny $nlitho $nDSz
+for n in $nco2 $nx $ny $nlitho $nDSz $n_basin
     do test $n -gt 0  2> /dev/null || istat=1
 done
 
 if [ $istat -ne 0 ]
 then
     echo ""
-    echo "ERROR: invalid resolution argument \"$resolution\""
+    echo "ERROR: invalid resolution argument \"$resolution\" or \"$n_basin\""
     exit 1
 fi
 
@@ -604,24 +625,6 @@ then
 	echo "  > periodic climatic parameter #$((k+1)) -- period: \"${period_values[$k]}\""
     fi
 fi
-
-
-## => Executable name:
-
-exec_name=geoclim
-exec_name=${exec_name}_${nco2}x${nx}x${ny}x${nlitho}-${len_cp[0]}x${len_cp[1]}x${len_cp[2]}x${len_cp[3]}x${len_cp[4]}
-if [ "$USE_DS" == "yes" ]
-then
-    exec_name=${exec_name}_DS
-    if [ "$DS_MODE" == "dynamic" ]
-    then
-        exec_name=${exec_name}-${nDSz}lev
-    else
-        exec_name=${exec_name}-SS
-    fi
-fi
-test "$USE_ECO" == "yes" && exec_name=${exec_name}_ECO
-exec_name=${exec_name}.exe
 
 
 ## climatic parameters end-of-reading mode
@@ -866,13 +869,42 @@ fi
 ############################################################################
 
 
+# Executable name:
+# ---------------
+
+exec_name=geoclim_B-${n_basin}_R-${nco2}x${nx}x${ny}x${nlitho}
+if [ ${len_cp[0]} -gt 1  -o  ${len_cp[1]} -gt 1  -o  ${len_cp[2]} -gt 1  -o  ${len_cp[3]} -gt 1  -o  ${len_cp[4]} -gt 1 ]
+then
+    exec_name=${exec_name}_P-${len_cp[0]}x${len_cp[1]}x${len_cp[2]}x${len_cp[3]}x${len_cp[4]}
+fi
+if [ "$USE_DS" == "yes" ]
+then
+    exec_name=${exec_name}_DS
+    if [ "$DS_MODE" == "dynamic" ]
+    then
+        exec_name=${exec_name}-${nDSz}lev
+    else
+        exec_name=${exec_name}-SS
+    fi
+fi
+test "$USE_ECO" == "yes" && exec_name=${exec_name}_ECO
+if [ "$lock_oxygen" == "1" -o "$lock_sulfur" == "1" ]
+then
+    exec_name=${exec_name}_LCK-
+    test "$lock_oxygen" == "1" && exec_name=${exec_name}O
+    test "$lock_sulfur" == "1" && exec_name=${exec_name}S
+fi
+
+exec_name=../executable/${exec_name}.exe
+
+
 # Write fortran include files:
 # ----------------------------
 
 rm -f source/shape.inc
 #     ^^^^^^^^^^^^^^^^
 echo '! File automatically generated by `build_GEOCLIM`'                 > source/shape.inc
-echo "integer, parameter :: nbasin = 10"                                >> source/shape.inc
+echo "integer, parameter :: nbasin = $n_basin"                          >> source/shape.inc
 echo "integer, parameter :: nclimber = $nco2"                           >> source/shape.inc
 echo "integer, parameter :: nlon = $nx"                                 >> source/shape.inc
 echo "integer, parameter :: nlat = $ny"                                 >> source/shape.inc
@@ -953,29 +985,33 @@ test "$all_fflags" == ""  || PRINT_MAKE_OPTIONS="$PRINT_MAKE_OPTIONS FFLAGS=\"$a
 # ---------------------------------------
 
 rm -f GEOCLIM_environment
-echo "#!/bin/bash"                 >  GEOCLIM_environment
-echo ""                            >> GEOCLIM_environment
-echo "export FC=$compiler"         >> GEOCLIM_environment
-test "$ncflags" == ""     || echo "export NETCDF_FLAGS='$ncflags'"    >> GEOCLIM_environment
-test "$main_fflags" == "" || echo "export main_flags='$main_fflags'"  >> GEOCLIM_environment
-test "$all_fflags" == ""  || echo "export FFLAGS='$all_fflags'"       >> GEOCLIM_environment
-echo "export execut=$exec_name"    >> GEOCLIM_environment
-echo "export USE_DS=$USE_DS"       >> GEOCLIM_environment
-echo "export USE_ECO=$USE_ECO"     >> GEOCLIM_environment
-test "$USE_DS" == "yes"   && echo "export DS_MODE=$DS_MODE"         >> GEOCLIM_environment
-echo "export CP_LOOP='$CP_LOOP'"   >> GEOCLIM_environment
-echo "export CP_KILL='$CP_KILL'"   >> GEOCLIM_environment
-test -z $comp_mode        || echo "export MODE=$comp_mode"          >> GEOCLIM_environment
-test -z $ncpath           || echo "export NCPATH=$ncpath"           >> GEOCLIM_environment
-echo ""                            >> GEOCLIM_environment
-echo "# Compilation command:"      >> GEOCLIM_environment
-echo "# make $PRINT_MAKE_OPTIONS"  >> GEOCLIM_environment
+echo "#!/bin/bash"                                                         >  GEOCLIM_environment
+echo ""                                                                    >> GEOCLIM_environment
+echo "export FC=$compiler"                                                 >> GEOCLIM_environment
+test "$ncflags" == ""     || echo "export NETCDF_FLAGS='$ncflags'"         >> GEOCLIM_environment
+test "$main_fflags" == "" || echo "export main_flags='$main_fflags'"       >> GEOCLIM_environment
+test "$all_fflags" == ""  || echo "export FFLAGS='$all_fflags'"            >> GEOCLIM_environment
+echo "export execut=$exec_name"                                            >> GEOCLIM_environment
+echo "export USE_DS=$USE_DS"                                               >> GEOCLIM_environment
+echo "export USE_ECO=$USE_ECO"                                             >> GEOCLIM_environment
+test "$USE_DS" == "yes"   && echo "export DS_MODE=$DS_MODE"                >> GEOCLIM_environment
+echo "export CP_LOOP='$CP_LOOP'"                                           >> GEOCLIM_environment
+echo "export CP_KILL='$CP_KILL'"                                           >> GEOCLIM_environment
+test -z $comp_mode        || echo "export MODE=$comp_mode"                 >> GEOCLIM_environment
+test -z $ncpath           || echo "export NCPATH=$ncpath"                  >> GEOCLIM_environment
+echo ""                                                                    >> GEOCLIM_environment
+echo "# NOTES:"                                                            >> GEOCLIM_environment
+echo "# current \"build_GEOCLIM\" command:"                                >> GEOCLIM_environment
+echo "#   $0 $bckp_args"                                                   >> GEOCLIM_environment
+echo "# \"Makefile\" compilation command (to be executed in \"source/\"):" >> GEOCLIM_environment
+echo "#   make $PRINT_MAKE_OPTIONS"                                        >> GEOCLIM_environment
 
 
 # Compile
 # -------
 
 rm -f build.log build.error
+test -d executable || mkdir executable
 cd source/
 
 test $reset -eq 1 && make clc > /dev/null
@@ -1010,12 +1046,10 @@ fi
 
 if [ $? -eq 0 ]
 then
-    test -d ../executable || mkdir ../executable
-    mv $exec_name ../executable/
     echo ""
     echo ""
     echo "compilation SUCCESFULL."
-    echo "Created file executable/$exec_name"
+    echo "Created file ${exec_name:3}"
     echo ""
     echo "To complete GEOCLIM configuration, edit files:"
     echo "    config/IO_CONDITIONS"
